## TensorFlow 2: Basic Operations

## Importing and checking TensorFlow
Let's import tensorflow and check it's version

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0
Keras version: 2.2.4-tf


Eager execution is the default in TensorFlow 2 and, as such, needs no special setup.

In [2]:
print("Eager execution is: {}".format(tf.executing_eagerly()))

Eager execution is: True


## TensorFlow variables
TensorFlow supports all the data types you would expect:  `tf.int32` ,  `tf.float64` and  `tf.complex64` for example. For a full list, please see: https://www.tensorflow.org/api_docs/python/tf/dtypes/DType
#### The default int type is `tf.int32` and the default float type is `tf.float32`

In [3]:
t0 = 44 # python variable
t1 = tf.Variable(13) # tensor variable
t2 = tf.Variable([ [ [0., 1., 2.], [2., 4., 5.] ], [ [3., 7., 8.], [6., 11., 23.] ] ])

In [4]:
t0, t1, t2

(44,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=13>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 2.,  4.,  5.]],
 
        [[ 3.,  7.,  8.],
         [ 6., 11., 23.]]], dtype=float32)>)

Alternatively, the datatype can be explicitly specified

In [5]:
f1 = tf.Variable(56.,dtype = tf.float64)
f1

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=56.0>

In [6]:
f1.dtype

tf.float64

To reassign a variable, use `var.assign()`

In [7]:
f1.assign(235.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=235.0>

## TensorFlow constants
TensorFlow constants may be declared as in the following example:

In [8]:
my_const = tf.constant(12)
my_const

<tf.Tensor: id=27, shape=(), dtype=int32, numpy=12>

In [9]:
my_const.numpy()

12

TensorFlow will infer the datatype, or it can be explicitly specified, as is the case with variables:

In [10]:
my_unit = tf.constant(1, dtype = tf.int64)
my_unit

<tf.Tensor: id=28, shape=(), dtype=int64, numpy=1>

## Shape of a tensor
The shape of a tensor is accessed via a property `shape`

In [11]:
my_tensor_var = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ])
print(my_tensor_var.shape)

(2, 2, 3)


Tensors maybe reshaped, preserving the total size,  and retain the same values,  as is often required for constructing neural networks.

In [12]:
my_tensor_reshape = tf.reshape(my_tensor_var,[2,6]) # 2 rows 6 cols
my_tensor_reshape2 = tf.reshape(my_tensor_var,[1,12]) # 1 rows 12 cols

In [13]:
my_tensor_reshape

<tf.Tensor: id=38, shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [14]:
my_tensor_reshape2

<tf.Tensor: id=41, shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

## Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [15]:
tf.rank(my_tensor_var)

<tf.Tensor: id=43, shape=(), dtype=int32, numpy=3>

In [16]:
tf.rank(my_tensor_var).numpy()

3

## Specifying an element of a tensor
Specifying an element of a tensor is performed, as you would expect, by specifying the required indices.

In [17]:
t3 = my_tensor_var[1, 0, 2] # slice 1, row 0, column 2
t3

<tf.Tensor: id=50, shape=(), dtype=float32, numpy=8.0>

### Find the size of a tensor

In [18]:
s = tf.size(input=my_tensor_var).numpy()
s

12

## Casting tensor to numpy variable

In [19]:
print(my_tensor_var.numpy())

print(my_tensor_var[1, 0, 2].numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
8.0


## Find data type of a tensor

In [20]:
t3.dtype

tf.float32

## Specifying element-wise primitive tensor operations
Element-wise primitive tensor operations are specified using, as you would expect, the overloaded operators `+`, `-`, `*`, and `/`, as here:

In [21]:
my_tensor_var*my_tensor_var

<tf.Tensor: id=61, shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [22]:
my_tensor_var+my_tensor_var

<tf.Tensor: id=64, shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  2.,  4.],
        [ 6.,  8., 10.]],

       [[12., 14., 16.],
        [18., 20., 22.]]], dtype=float32)>

## Broadcasting:
Element-wise tensor operations support broadcasting in the same way that NumPy arrays do. The simplest example is that of multiplying a tensor by a scalar:

In [23]:
my_tensor_var4 = my_tensor_var*4
print(my_tensor_var4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


## Transposing TensorFlow and matrix multiplication
To transpose a matrix and matrix multiplication eagerly, use the following:

In [24]:
u = tf.constant([[1,4,2]])
v = tf.constant([[3,2,4]])
tf.matmul(u, tf.transpose(a=v))

<tf.Tensor: id=72, shape=(1, 1), dtype=int32, numpy=array([[19]], dtype=int32)>

All of the operations that are available for tensors that form part of a computational graph are also available for eager execution variables.

## Casting a tensor to another datatype

In [25]:
my_tensor_var4

<tf.Tensor: id=67, shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

In [26]:
my_tensor_cast = tf.cast(my_tensor_var4, dtype=tf.float64)
my_tensor_cast

<tf.Tensor: id=73, shape=(2, 2, 3), dtype=float64, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]])>

with truncation

In [27]:
with_trunc = tf.cast(tf.constant(4.9), dtype=tf.int32)
with_trunc

<tf.Tensor: id=75, shape=(), dtype=int32, numpy=4>

In [28]:
#adding tensors
i = tf.Variable(12)
j = tf.Variable(56)
tf.add(i,j)

<tf.Tensor: id=92, shape=(), dtype=int32, numpy=68>

## Ragged Tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.

There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.

The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [29]:
ragged =tf.ragged.constant([[7, 2, 6, 1,5], [], [4, 10, 7,6,7,8,9], [8], [6,7,8]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[7, 2, 6, 1, 5], [], [4, 10, 7, 6, 7, 8, 9], [8], [6, 7, 8]]>
tf.Tensor([7 2 6 1 5], shape=(5,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7  6  7  8  9], shape=(7,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7 8], shape=(3,), dtype=int32)


A common way of creating a ragged array is by using the tf.RaggedTensor.from_row_splits() method, which has the following signature:

<pre>@classmethod
from_row_splits(
    cls,
    values,
    row_splits,
    name=None
)</pre>

Here, values is a list of the values to be turned into the ragged array, and `row_splits` is a list of the positions where the value list is to be split, so that the values for row `ragged[i]` are stored in `ragged.values[ragged.row_splits[i]:ragged.row_splits[i+1]]`:

In [30]:
print(tf.RaggedTensor.from_row_splits(values=[8, 2, 6, 1, 4, 44, 7, 58, 6, 7],row_splits=[0, 4, 4, 7, 8, 10]))

<tf.RaggedTensor [[8, 2, 6, 1], [], [4, 44, 7], [58], [6, 7]]>


## Some useful TensorFlow functions
Now let's look at some useful TensorFlow operations, especially within the context of neural network programming.

### Finding the squared difference between two tensors
The method is as follows:
`tf.math.squared.difference( x,  y, name=None)`

In [31]:
x = [1,3,5,7,11,7,9]
y = 7
s = tf.math.squared_difference( x,  y) #() x-y)*(x-y) with broadcasting
s

<tf.Tensor: id=261, shape=(7,), dtype=int32, numpy=array([36, 16,  4,  0, 16,  0,  4], dtype=int32)>

Note that the Python variables, `x` and `y`, are cast into tensors and that y is then broadcast across `x` in this example. So, for example, the first calculation is $$ (1-7)^2 = 36 $$

### Finding a mean
The following is the signature of `tf.reduce_mean()`.

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [32]:
numbers = tf.constant([[4., 6.], [5., 3.]])

### Finding the mean across all axes
Find the mean across all axes (that is, use the default axis = None) with this:

In [33]:
tf.reduce_mean(input_tensor=numbers) #( 4. + 6. + 5. + 3.)/4 = 4.5

<tf.Tensor: id=264, shape=(), dtype=float32, numpy=4.5>

### Find mean across columns (i.e. reduce rows)

In [34]:
tf.reduce_mean(input_tensor=numbers, axis=0) # [ (4. + 5. )/2 , (6. + 3.)/2 ].

<tf.Tensor: id=266, shape=(2,), dtype=float32, numpy=array([4.5, 4.5], dtype=float32)>

When `keepdims` is `True`, the reduced axis is retained with a length of 1:

In [35]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=268, shape=(1, 2), dtype=float32, numpy=array([[4.5, 4.5]], dtype=float32)>

### Find mean across rows (i.e. reduce columns)

In [36]:
tf.reduce_mean(input_tensor=numbers, axis=1) # [ (4. + 6. )/2 , (5. + 3. )/2]

<tf.Tensor: id=270, shape=(2,), dtype=float32, numpy=array([5., 4.], dtype=float32)>

In [37]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: id=272, shape=(2, 1), dtype=float32, numpy=
array([[5.],
       [4.]], dtype=float32)>

## Generating tensors filled with random values

Random values are frequently required when developing neural networks, for example, when initializing weights and biases. TensorFlow provides a number of methods for generating these random values.

### Using `tf.random.normal()`

`tf.random.normal()` outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

The required signature is as follows:

`tf. random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [38]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)

<tf.Tensor: id=278, shape=(3, 2), dtype=float32, numpy=
array([[11.06086 ,  6.001184],
       [10.96436 ,  8.614066],
       [ 9.396932, 11.82612 ]], dtype=float32)>

In [39]:
ran = tf.random.normal(shape = (6,2), mean=10.0, stddev=2.0)
print(ran)

tf.Tensor(
[[ 9.567563  13.20314  ]
 [ 6.0821037 10.633168 ]
 [10.068582  12.056449 ]
 [10.883337  10.063499 ]
 [11.978831   8.922867 ]
 [11.127165   9.549822 ]], shape=(6, 2), dtype=float32)


### Using `tf.random.uniform()`

The required signature is this:
`tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None,  name=None)`

This outputs a tensor of the given shape filled with values from a uniform distribution in the range `minval` to `maxval`, where the lower bound is inclusive but the upper bound isn't.

In [40]:
tf.random.uniform(shape = (4,4),  minval=0, maxval=None, dtype=tf.float32, seed=None,  name=None)

<tf.Tensor: id=291, shape=(4, 4), dtype=float32, numpy=
array([[0.82856905, 0.15087605, 0.6246054 , 0.2769431 ],
       [0.55981874, 0.6704706 , 0.05041134, 0.8613808 ],
       [0.52797985, 0.03558445, 0.60545075, 0.04075563],
       [0.9636085 , 0.03566635, 0.99371207, 0.69405365]], dtype=float32)>

In [41]:
ran_uni = tf.random.uniform(shape = (2,20), maxval=20, dtype=tf.int32)
print(ran_uni)

tf.Tensor(
[[ 4 11  7  5  8 15 14 18  3  8 14  5  4  5  5  9  0 17  8  2]
 [17  1  2 18  5 17 14  6 16  1 10 19 15 14 11  8 12  5  0  6]], shape=(2, 20), dtype=int32)


Note that, for both of these random operations, if you want the random values generated to be repeatable, then use `tf.random.set_seed()`. Use of a non-default datatype is also shown here:

In [42]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,20), maxval=10, dtype = tf.int32)
ran2 =  tf.random.uniform(shape = (2,20), maxval=10, dtype = tf.int32)
print(ran1) #Call 1
print(ran2)

tf.random.set_seed(11) #same seed
ran1 = tf.random.uniform(shape = (2,20), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,20), maxval=10, dtype = tf.int32)
print(ran1)
print(ran2)

tf.Tensor(
[[4 6 5 2 8 8 4 7 8 4 7 4 4 9 7 6 0 6 7 0]
 [0 6 0 4 8 4 8 1 7 4 2 8 2 4 3 4 8 9 9 3]], shape=(2, 20), dtype=int32)
tf.Tensor(
[[9 7 9 4 0 1 1 3 1 4 7 2 4 9 9 5 2 0 7 5]
 [3 0 8 8 4 6 3 2 7 4 6 5 2 4 9 0 4 6 4 7]], shape=(2, 20), dtype=int32)
tf.Tensor(
[[4 6 5 2 8 8 4 7 8 4 7 4 4 9 7 6 0 6 7 0]
 [0 6 0 4 8 4 8 1 7 4 2 8 2 4 3 4 8 9 9 3]], shape=(2, 20), dtype=int32)
tf.Tensor(
[[9 7 9 4 0 1 1 3 1 4 7 2 4 9 9 5 2 0 7 5]
 [3 0 8 8 4 6 3 2 7 4 6 5 2 4 9 0 4 6 4 7]], shape=(2, 20), dtype=int32)


## Using `tf.function`

`tf.function` is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function `(func).` `tf.function` is new to TensorFlow 2.

Its signature is as follows:
<pre>tf.function(
    func=None,
    input_signature=None,
    autograph=True,
    experimental_autograph_options=None
)
</pre>

In [43]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 5) + y**3)

f2 = tf.function(f1)

x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph

assert f1(x,y).numpy() == f2(x,y).numpy()