<a href="https://colab.research.google.com/github/sanikamal/deep-learning-atoz/blob/master/pytorch_example/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [0]:
import torch

In [0]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[ 0.1935,  1.6394,  0.7218],
        [ 1.2603, -0.1931,  0.4915],
        [-1.5562, -0.2090, -0.1647],
        [-0.4638, -0.2046, -0.2044]], requires_grad=True)

In [4]:
w.requires_grad_(False)
w

tensor([[ 0.1935,  1.6394,  0.7218],
        [ 1.2603, -0.1931,  0.4915],
        [-1.5562, -0.2090, -0.1647],
        [-0.4638, -0.2046, -0.2044]])

In [5]:
w.requires_grad_(True)

tensor([[ 0.1935,  1.6394,  0.7218],
        [ 1.2603, -0.1931,  0.4915],
        [-1.5562, -0.2090, -0.1647],
        [-0.4638, -0.2046, -0.2044]], requires_grad=True)

In [6]:
y = torch.exp(w)
print(y)

tensor([[1.2135, 5.1523, 2.0582],
        [3.5265, 0.8244, 1.6348],
        [0.2109, 0.8114, 0.8482],
        [0.6289, 0.8150, 0.8151]], grad_fn=<ExpBackward>)


In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(1.5449, grad_fn=<MeanBackward0>)


In [9]:
print(w.grad)

None


In [0]:
outp.backward()

In [11]:
print(w.grad)

tensor([[0.1011, 0.4294, 0.1715],
        [0.2939, 0.0687, 0.1362],
        [0.0176, 0.0676, 0.0707],
        [0.0524, 0.0679, 0.0679]])


In [12]:
print(w.detach())

tensor([[ 0.1935,  1.6394,  0.7218],
        [ 1.2603, -0.1931,  0.4915],
        [-1.5562, -0.2090, -0.1647],
        [-0.4638, -0.2046, -0.2044]])


In [13]:
print(outp.requires_grad)

with torch.no_grad():
  outp = (w+y).mean()
  
print(outp.requires_grad)  

True
False
